version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8.0
    ports:
      - 3307:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: abc
      MYSQL_DATABASE: abc
      MYSQL_USER: abc
      MYSQL_PASSWORD: abc
    volumes:
      - mysql-db:/var/lib/mysql

volumes:
  mysql-db:
