name: ci

on: 
  push:
    branches: main

jobs: 
  build:
    name: build stage
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: login to docker hub
        uses: docker/login-action@v3
        with: 
          username: $ {{ sercrets.DOCKER_USERNAME }}
          password: $ {{ sercrets.DOCKER_TOKEN }}
      - name: build and push to docker master
        uses: docker/build-push-action@v2
        with: 
          context: .
          push: true
          tags: go-sv/docker:latest, go-sv/docker:${{ github.run_number }}